### PR TITLE
Vueify all frontend pages, add style checks

### PR DESCRIPTION
**Pull request by gbougakov**
All pages have been Vuefied and all responsibility issues (#1) were fixed

### CODE REVIEW

**Comment by gbougakov** [comment]
I also think that we should delete the [`html-mockups`](https://github.com/gbougakov/JoinMyCall/tree/html-mockups) branch

**Comment by KumarAbhirup** [comment]
Sure, you may delete the `html-mockups` branch. Will review this today.

**Comment by KumarAbhirup** [comment]
I think we should now be deleting entire `html-mockups` folder.

**Comment by gbougakov** [comment]
html-mockups branch was deleted and master branch was initialised as an orphan branch, so, there is no html-mockups folder there

**Comment by gbougakov** [comment]
Filed a now CLI bug. zeit/now-cli#2417

**Pull request merged**
